travis:
  secure:
    BINSTAR_TOKEN: lai6M835CplqJBOobpNyHqWSZQ15CtrX2V8si7IiugYCRFFdFz8s8YTX3fUWrcZ3Z9xxV9Uz09TbPDE2XePDGI2FjP2L9L8YC8lGtGcMfcEWTEvCHQzM31y64hfgMjidXfB8fDz6X+11Na89IVvaFH1RcVJCvjKIxctW5NCgBaFloLOArcmTONngIzywaKj20MXLJG3VEPiJv+lwlsCtBVAIDXq1oYoq+Hpbfv9CtAU0V9n71Ok6s5PYzcEnbyT97E78v5+QUDOTh6IENMNViOZIeW98d4gyPjYhdAes/4FHY0p4OyVl2Xwtkb0S5ueg8VupN10e/AKPFt7zVpIbdLvIoVwG/h/TcXbwnsAH2xIPeMyQJfwLkqamGaRcC9ZxN3qQOZt5IgbODfVOrGtfWKQD4sSws67dzgwW0CCgbcpJwCNBtKXl3mGPf4TTqQ3/+EOvfyL9pVekFIMdfQYZETQd80JwvE78FJ8SORkpGXa7EacQauHzXtHSX07xdPuTxJP3v0Qy2tb1lx4qTNA+JGYwK6ZtR/EBEUWyFIWZ/sg4jVGKwfg3/8wCw2pMp6/6TOsy0ZJnDbUyeXuMrbEbqBM+5OUPrl8Xl+9oy8RZDhMMMee8TZGzYX82iqo9jJAfswdSwFmhr5NF1OiSO0L1+F3LOIasSkClT/DHA6qNw6k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
